export const questionsFake = [
  {
    id: '1',
    number: 'Câu 1',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "anh em ut it oi",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '2',
    number: 'Câu 2',
    question: "Một vật dao lượt là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '3',
    number: 'Câu 3',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '4',
    number: 'Câu 4',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '5',
    number: 'Câu 5',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '6',
    number: 'Câu 6',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '7',
    number: 'Câu 7',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },
  {
    id: '8',
    number: 'Câu 8',
    question: "Một vật dao động điều hòa trên trục Ox quanh vị trí cân bằng O. Gọi A, ω và φ lần lượt là biên độ, tần số góc và pha ban đầu của dao động. Biểu thức li độ của vật theo thời gian t là",
    answers: [
      "A. x = Acos(ωt + φ).",
      "B. x = Acos(ωt + φ).",
      "C. x = Acos(ωt + φ).",
      "D. x = Acos(ωt + φ).",
    ],
    true_answer: "A. x = Acos(ωt + φ).",
    instructions: "",
    level: '3',
    tags: [
      "Dao động cơ",
      "Chương 1",
      "Dao động điều hòa",
    ],
    average_time: 1000,
  },

];

export const examTestsFake = [
  {
    "id": 1,
    "title": "Đề kiểm tra 15 phút chương 1: Dao động cơ - Đề số 01",
    "number_question": 10,
    "type": "Đề kiểm tra 15 phút",
    "time": 900,
    "tags": [
      "Dao động cơ",
      "Dao động",
    ],
    "points": "100",
  },
  {
    "id": 2,
    "title": "Đề kiểm tra 50 phút chương 1: Dao động cơ - Đề số 01",
    "number_question": 40,
    "type": "Đề kiểm tra 15 phút",
    "time": 3000,
    "tags": [
      "Dao động cơ",
      "Dao động",
    ],
    "points": "100",
  },
  {
    "id": 2,
    "title": "Đề kiểm tra 50 phút chương 1: Dao động cơ - Đề số 01",
    "number_question": 40,
    "type": "Đề kiểm tra 15 phút",
    "time": 3000,
    "tags": [
      "Dao động cơ",
      "Dao động",
    ],
    "points": "100",
  },
  {
    "id": 2,
    "title": "Đề kiểm tra 50 phút chương 1: Dao động cơ - Đề số 01",
    "number_question": 40,
    "type": "Đề kiểm tra 15 phút",
    "time": 3000,
    "tags": [
      "Dao động cơ",
      "Dao động",
    ],
    "points": "100",
  },
];

export const userFake = [
  {
    "id": 1,
    "name": 'Nguyễn Việt Hải',
    "username": 'chien@gmail.com',
    "average_point": '7.8',
    "total_time": '10',
  },
  {
    "id": 1,
    "name": 'Nguyễn Văn Chién',
    "username": 'chien@gmail.com',
    "average_point": '7.2',
    "total_time": '1000',
  },
  {
    "id": 2,
    "name": 'Phan Trọng Tình',
    "username": 'tinh@gmail.com',
    "average_point": '7.8',
    "total_time": '256',
  },
  {
    "id": 1,
    "name": 'Lê Đức Hải',
    "username": 'hải@gmail.com',
    "average_point": '7.8',
    "total_time": '200',
  },
  {
    "id": 1,
    "name": 'Trung Thu',
    "username": 'thu@gmail.com',
    "average_point": '6.2',
    "total_time": '320',
  }
]
