export const TAGS = [
  'Chương 1. Dao động cơ',
  'Chương 2. Sóng cơ và sóng âm',
  'Chương 3. Dòng điện xoay chiều',
  'Chương 4. Dao động điển từ',
  'Chương 5. Sóng anh sáng',
  'Chương 6. Lượng tử ánh sáng',
  'Chương 7. Vật lý hạt nhân',
  'Dao động điều hòa',
  'Con lắc lò xo',
  'Con lắc đơn',
  'Dao động tắt dần - Dao động cưỡng bức',
  'Tổng hợp các dao động điều hòa',
  'Sóng cơ và sự truyền sóng cơ',
  'Giao thoa sóng',
  'Sóng dừng',
  'Sóng âm',
  'Đại cương về dòng điện xoay chiều',
  'Các loại điện xoay chiều',
  'Mạch có R, L, C mắc nối tiếp',
  'Công suốt của mạch điện xoay chiều',
  'Truyền tải điện năng, máy biến áp',
  'Máy phát điện, động cơ điện',
  'Mạch dao động',
  'Điện từ trường, sóng điện từ, truyền thông',
  'Tán sắc ánh sáng',
  'Nhiều xạ ánh sáng, giao thoa ánh sáng',
  'Quang phổ',
  'Tia hồng ngoại, tia tử ngoại, tia X',
  'Hiện tượng quang điện, thuyết lượng tử ánh sáng',
  'Mẫu nguyên tử Bo',
  'Tính chất của cấu tạo hạt nhân',
  'Năng lượng liên kết, phản ứng hật nhân',
  'Phóng xạ',
  'Phản ứng phân hạch, phản ứng nhiệt hạch',
];

export default {};
